name: update-api-docs
run-name: ${{ github.actor }} updated API docs
on: [push]
jobs:
  publish-api-spec:
    runs-on: ubuntu-latest
    permissions:
     contents: write
     pull-requests: write
     
    steps:
    # This step checks out a copy of your repository.
    - name: Get repo
      uses: actions/checkout@v4
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
    - name: Docker Run
  # You may pin to the exact commit or the version.
  # uses: tj-actions/docker-run@1d25a677da8f1243a138dc5db21e307e92986ffe
      uses: tj-actions/docker-run@v2.2.1  
      env:
          DIR_GHP: "gh-pages"
      with:
          # Docker image
          image: funbox/blueprinter
          # Container name
          name: blueprinter
          # Command to run
          args: -i api.apib -o "${DIR_GHP}"/index.html
          # Options to pass to docker run
          options: -v $(pwd):/app 
    #- name: Use Node.js
    #  uses: actions/setup-node@v3
    #  with:
    #    node-version: '20.x'
        
    - name: Run publish.sh to generate index.html
      #run: git update-index --chmod=-x  bin/compile_docs.sh
      run: bash publish.sh 
