name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  publish-api-spec:
    runs-on: ubuntu-latest
    steps:
    # This step checks out a copy of your repository.
    - uses: actions/checkout@v4
    - uses: Bwen/action-ghp-sync@v1-beta
      with:
        source_dir: tobyscales/openmetadataio-apidef
        build_script: /home/runner/work/openmetadataio-apidef/openmetadataio-apidef/publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
