name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  publish-api-spec:
    runs-on: ubuntu-latest
    steps:
    - uses: Bwen/action-ghp-sync@v1-beta
      with:
        source_dir: .
        build_script: bin/compile_docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
